#!/usr/bin/env python3
"""
Test script for Specimen typography system compiler.
Verifies that the compiler and exports work correctly.
"""

import sys
import os
import json

# Add scripts to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'scripts'))

from specimen_compiler import compile_from_config
from specimen_exports import (
    export_css_variables,
    export_tailwind_config,
    export_scss_variables,
    export_figma_tokens,
    export_json
)


def test_basic_compilation():
    """Test basic typography system compilation."""
    print("Testing basic compilation...")
    
    config = {
        'base_size': 16,
        'ratio': 'minor_third',
        'mode': 'balanced'
    }
    
    result = compile_from_config(config)
    
    if not result['ok']:
        print(f"❌ Compilation failed: {result['message']}")
        return False
    
    system = result['typography_system']
    
    # Verify structure
    assert 'version' in system
    assert 'meta' in system
    assert 'config' in system
    assert 'fonts' in system
    assert 'scale' in system
    assert 'line_heights' in system
    assert 'letter_spacing' in system
    assert 'semantic' in system
    
    # Verify engine metadata
    assert system['meta']['engine']['name'] == 'specimen'
    
    print("✅ Basic compilation works!")
    return True


def test_all_ratios():
    """Test all available type scale ratios."""
    print("\nTesting all scale ratios...")
    
    ratios = [
        'minor_second', 'major_second', 'minor_third', 'major_third',
        'perfect_fourth', 'augmented_fourth', 'perfect_fifth', 'golden_ratio'
    ]
    
    for ratio in ratios:
        result = compile_from_config({'base_size': 16, 'ratio': ratio})
        if not result['ok']:
            print(f"❌ Ratio '{ratio}' failed")
            return False
        assert result['typography_system']['config']['ratio'] == ratio
    
    print(f"✅ All {len(ratios)} ratios work!")
    return True


def test_all_modes():
    """Test all available modes."""
    print("\nTesting all modes...")
    
    modes = ['tight', 'balanced', 'loose']
    
    for mode in modes:
        result = compile_from_config({'base_size': 16, 'ratio': 'minor_third', 'mode': mode})
        if not result['ok']:
            print(f"❌ Mode '{mode}' failed")
            return False
        
        system = result['typography_system']
        scale_count = len(system['scale'])
        
        # Verify expected scale sizes
        if mode == 'tight':
            assert scale_count >= 5  # 4 up, 1 down, base
        elif mode == 'balanced':
            assert scale_count >= 7  # 5 up, 2 down, base  
        elif mode == 'loose':
            assert scale_count >= 8  # 6 up, 2 down, base
    
    print(f"✅ All {len(modes)} modes work!")
    return True


def test_exports():
    """Test all export formats."""
    print("\nTesting export formats...")
    
    result = compile_from_config({'base_size': 16, 'ratio': 'minor_third'})
    system = result['typography_system']
    
    # Test CSS Variables
    css = export_css_variables(system)
    assert '--font-primary' in css
    assert '--text-base' in css
    assert 'Typography System - Generated by Specimen' in css
    
    # Test Tailwind Config
    tailwind = export_tailwind_config(system)
    assert 'fontFamily' in tailwind
    assert 'fontSize' in tailwind
    assert 'Typography System - Generated by Specimen' in tailwind
    
    # Test SCSS Variables
    scss = export_scss_variables(system)
    assert '$font-primary' in scss
    assert '$text-base' in scss
    assert 'Typography System - Generated by Specimen' in scss
    
    # Test Figma Tokens
    figma_result = export_figma_tokens(system)
    assert figma_result['ok']
    tokens = figma_result['tokens']
    assert 'typography' in tokens
    
    # Test JSON
    json_output = export_json(system)
    parsed = json.loads(json_output)
    assert parsed['version'] == '1.0'
    
    print("✅ All export formats work!")
    return True


def test_font_families():
    """Test custom font families."""
    print("\nTesting custom font families...")
    
    config = {
        'base_size': 16,
        'ratio': 'minor_third',
        'font_family_primary': 'Inter, system-ui, sans-serif',
        'font_family_secondary': 'Playfair Display, serif',
        'font_family_mono': 'JetBrains Mono, monospace'
    }
    
    result = compile_from_config(config)
    system = result['typography_system']
    
    assert system['fonts']['families']['primary'] == 'Inter, system-ui, sans-serif'
    assert system['fonts']['families']['secondary'] == 'Playfair Display, serif'
    assert system['fonts']['families']['mono'] == 'JetBrains Mono, monospace'
    
    print("✅ Custom font families work!")
    return True


def main():
    """Run all tests."""
    print("=" * 60)
    print("Specimen Typography System Compiler - Test Suite")
    print("=" * 60)
    
    tests = [
        test_basic_compilation,
        test_all_ratios,
        test_all_modes,
        test_exports,
        test_font_families
    ]
    
    passed = 0
    failed = 0
    
    for test in tests:
        try:
            if test():
                passed += 1
            else:
                failed += 1
        except Exception as e:
            print(f"❌ Test failed with exception: {e}")
            failed += 1
    
    print("\n" + "=" * 60)
    print(f"Results: {passed} passed, {failed} failed")
    print("=" * 60)
    
    if failed == 0:
        print("\n🎉 All tests passed! Specimen is working correctly.")
        return 0
    else:
        print(f"\n⚠️  {failed} test(s) failed.")
        return 1


if __name__ == '__main__':
    sys.exit(main())
