#!/usr/bin/env python3
"""
Specimen Exports - Typography System Export Formats
Exports typography systems to CSS, Tailwind, Figma tokens, and other formats.
"""

import json
from typing import Dict, Any


def export_css_variables(system: Dict[str, Any]) -> str:
    """
    Export typography system as CSS custom properties.
    
    Args:
        system: Typography system dictionary from compiler
    
    Returns:
        CSS string with custom properties
    """
    css_lines = [
        "/* Typography System - Generated by Specimen */",
        "",
        ":root {",
        "  /* Font Families */"
    ]
    
    # Font families
    for name, stack in system['fonts']['families'].items():
        css_lines.append(f"  --font-{name}: {stack};")
    
    css_lines.append("")
    css_lines.append("  /* Font Weights */")
    
    # Weights
    for name, value in system['fonts']['weights'].items():
        css_lines.append(f"  --font-weight-{name}: {value};")
    
    css_lines.append("")
    css_lines.append("  /* Type Scale */")
    
    # Type scale
    for step, props in system['scale'].items():
        css_lines.append(f"  --text-{step}: {props['rem']}rem;")
    
    css_lines.append("")
    css_lines.append("  /* Line Heights */")
    
    # Line heights
    for step, lh in system['line_heights'].items():
        css_lines.append(f"  --leading-{step}: {lh};")
    
    css_lines.append("")
    css_lines.append("  /* Letter Spacing */")
    
    # Letter spacing
    for step, ls in system['letter_spacing'].items():
        css_lines.append(f"  --tracking-{step}: {ls};")
    
    css_lines.append("}")
    
    # Semantic utility classes
    css_lines.append("")
    css_lines.append("/* Semantic Type Styles */")
    
    for semantic, scale_key in system['semantic'].items():
        scale_props = system['scale'][scale_key]
        lh = system['line_heights'][scale_key]
        ls = system['letter_spacing'][scale_key]
        
        css_lines.append(f".{semantic} {{")
        css_lines.append(f"  font-size: {scale_props['rem']}rem;")
        css_lines.append(f"  line-height: {lh};")
        css_lines.append(f"  letter-spacing: {ls};")
        css_lines.append("}")
    
    return "\n".join(css_lines)


def export_tailwind_config(system: Dict[str, Any]) -> str:
    """
    Export typography system as Tailwind config extension.
    
    Args:
        system: Typography system dictionary from compiler
    
    Returns:
        JavaScript string for tailwind.config.js
    """
    js_lines = [
        "// Typography System - Generated by Specimen",
        "// Add to your tailwind.config.js",
        "",
        "export default {",
        "  theme: {",
        "    extend: {",
        "      fontFamily: {"
    ]
    
    # Font families
    for name, stack in system['fonts']['families'].items():
        # Convert to array format for Tailwind
        fonts = [f"'{f.strip()}'" for f in stack.split(',')]
        fonts_str = ', '.join(fonts)
        js_lines.append(f"        {name}: [{fonts_str}],")
    
    js_lines.append("      },")
    js_lines.append("      fontWeight: {")
    
    # Weights
    for name, value in system['fonts']['weights'].items():
        js_lines.append(f"        '{name}': {value},")
    
    js_lines.append("      },")
    js_lines.append("      fontSize: {")
    
    # Type scale with line heights
    for step, props in system['scale'].items():
        lh = system['line_heights'][step]
        js_lines.append(f"        '{step}': ['{props['rem']}rem', {{ lineHeight: '{lh}' }}],")
    
    js_lines.append("      },")
    js_lines.append("      letterSpacing: {")
    
    # Letter spacing
    for step, ls in system['letter_spacing'].items():
        js_lines.append(f"        '{step}': '{ls}',")
    
    js_lines.append("      },")
    js_lines.append("    },")
    js_lines.append("  },")
    js_lines.append("};")
    
    return "\n".join(js_lines)


def export_scss_variables(system: Dict[str, Any]) -> str:
    """
    Export typography system as SCSS variables.
    
    Args:
        system: Typography system dictionary from compiler
    
    Returns:
        SCSS string with variables
    """
    scss_lines = [
        "// Typography System - Generated by Specimen",
        "",
        "// Font Families"
    ]
    
    # Font families
    for name, stack in system['fonts']['families'].items():
        scss_lines.append(f"$font-{name}: {stack};")
    
    scss_lines.append("")
    scss_lines.append("// Font Weights")
    
    # Weights
    for name, value in system['fonts']['weights'].items():
        scss_lines.append(f"$font-weight-{name}: {value};")
    
    scss_lines.append("")
    scss_lines.append("// Type Scale")
    
    # Type scale
    for step, props in system['scale'].items():
        scss_lines.append(f"$text-{step}: {props['rem']}rem;")
    
    scss_lines.append("")
    scss_lines.append("// Line Heights")
    
    # Line heights
    for step, lh in system['line_heights'].items():
        scss_lines.append(f"$leading-{step}: {lh};")
    
    scss_lines.append("")
    scss_lines.append("// Letter Spacing")
    
    # Letter spacing
    for step, ls in system['letter_spacing'].items():
        scss_lines.append(f"$tracking-{step}: {ls};")
    
    # Semantic map
    scss_lines.append("")
    scss_lines.append("// Semantic Mappings")
    scss_lines.append("$semantic-type: (")
    
    for semantic, scale_key in system['semantic'].items():
        scss_lines.append(f"  '{semantic}': '{scale_key}',")
    
    scss_lines.append(");")
    
    return "\n".join(scss_lines)


def export_figma_tokens(system: Dict[str, Any]) -> Dict[str, Any]:
    """
    Export typography system as Figma design tokens (Tokens Studio format).
    
    Args:
        system: Typography system dictionary from compiler
    
    Returns:
        Dictionary containing tokens structure and result status
    """
    tokens = {
        "typography": {
            "fontFamilies": {},
            "fontWeights": {},
            "fontSize": {},
            "lineHeights": {},
            "letterSpacing": {},
            "paragraphSpacing": {}
        }
    }
    
    # Font families
    for name, stack in system['fonts']['families'].items():
        tokens["typography"]["fontFamilies"][name] = {
            "value": stack.split(',')[0].strip(),
            "type": "fontFamilies"
        }
    
    # Font weights
    for name, value in system['fonts']['weights'].items():
        tokens["typography"]["fontWeights"][name] = {
            "value": str(value),
            "type": "fontWeights"
        }
    
    # Font sizes
    for step, props in system['scale'].items():
        tokens["typography"]["fontSize"][step] = {
            "value": f"{props['px']}",
            "type": "fontSizes"
        }
    
    # Line heights
    for step, lh in system['line_heights'].items():
        tokens["typography"]["lineHeights"][step] = {
            "value": str(lh),
            "type": "lineHeights"
        }
    
    # Letter spacing
    for step, ls in system['letter_spacing'].items():
        tokens["typography"]["letterSpacing"][step] = {
            "value": ls,
            "type": "letterSpacing"
        }
    
    return {
        'ok': True,
        'tokens': tokens,
        'message': 'Figma tokens exported successfully'
    }


def export_json(system: Dict[str, Any]) -> str:
    """
    Export typography system as formatted JSON.
    
    Args:
        system: Typography system dictionary from compiler
    
    Returns:
        Pretty-printed JSON string
    """
    return json.dumps(system, indent=2)


if __name__ == '__main__':
    # Test with a sample system
    from specimen_compiler import compile_from_config
    
    result = compile_from_config({
        'base_size': 16,
        'ratio': 'minor_third'
    })
    
    if result['ok']:
        system = result['typography_system']
        
        print("=== CSS Variables ===")
        print(export_css_variables(system))
        print("\n=== Tailwind Config ===")
        print(export_tailwind_config(system))
